### PR TITLE
Modify bearing block to accept Nyloc nuts

### PR DESCRIPTION
**Pull request by PeeJay**
Also adds a bit of strength to stop nut tearing it's mounting out.

Signed-off-by: Paul Jones paul@pauljones.id.au

### CODE REVIEW

**Comment by firepick1** [comment]
Paul, I'm merging your change into 3D0001L--I like it.

**Comment by firepick1** [comment]
Neil, sorry about the premature merge. I didn't realize that Paul had changed other dimensions as well.

**Comment by FlyingLotus1983** [comment]
Karl, feel free to merge into dev-loose or any other branch, but I'm trying
to keep a close eye on what goes into 'dev'.  It's already starting to get
a bit out of hand, and is going to cause a lot of confusion if it's not
handled well.  Already we've got lots of incorrect part identifiers,
mismatching STLs and AD_PRT's, and outdated wiki pictures.  'Dev' may lag a
bit behind all the bleeding edge stuff but that will at least ensure that
what is in there is documented.

**Comment by PeeJay** [comment]
I tried to modify only the captive nut holder and it's supports but I may have inadvertently changed other things by mistake. I did notice that the assembly didn't quite look right, but I'm a noob at Cubify and I'm not sure if I updated it correctly. 
I assembled them last night and I didn't rip them to pieces this time :) Some of the nuts were not quite a press fit into their holes so I think that dimension needs to go from 6.0 to 5.8mm

**Comment by FlyingLotus1983** [comment]
If you go way back to the first iteration of this piece, I had the nut traps where the nuts went in from the top (very similar to what you have now). The problem that I had was that when you pushed an M3 screw in to attach, they would sometimes pop out.  I later changed them so they go in from the side which fixed that problem.  Some people have reported that they split, and I think I know how to fix this while keep the nuts going in from the side, I've just not gotten to it yet.

**Comment by firepick1** [comment]
Paul, I converted 3D0001L to upside down M3 nut trap and it works great:

https://github.com/firepick-delta/firepick-delta/blob/dev-loose/mechanical/3Dxxxx%20-%203D%20printed%20parts/STL/3D0001L%20Delta%20608%20bearing%20block.stl

Since I am printing so many of these, the new trap will save me a lot of
time during assembly. I also increased the 5.7 hex to 5.8mm for loose,
drop-in fit.

On Mon, Nov 10, 2014 at 3:45 PM, Neil Jansen notifications@github.com
wrote:

> If you go way back to the first iteration of this piece, I had the nut
> traps where the nuts went in from the top (very similar to what you have
> now). The problem that I had was that when you pushed an M3 screw in to
> attach, they would sometimes pop out. I later changed them so they go in
> from the side which fixed that problem. Some people have reported that they
> split, and I think I know how to fix this while keep the nuts going in from
> the side, I've just not gotten to it yet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firepick-delta/firepick-delta/pull/5#issuecomment-62477723
> .

## 

Karl Lew
FIREPICK SERVICES LLC
karl@firepick.org
www.firepick.org

**Pull request merged**
